SELECT COUNT(*), COUNT(DISTINCT siren)
FROM TableC;

SELECT COUNT(*), COUNT(DISTINCT siren)
FROM TableC
WHERE opened IS NOT NULL;

SELECT COUNT(*), COUNT(DISTINCT siren)
FROM TableC
WHERE answerDate IS NOT NULL;

SELECT COUNT(*), COUNT(DISTINCT siren)
FROM TableC
WHERE need = '1';
