CREATE TABLE insee_StockEtablissement
(
siren BIGINT NOT NULL,
nic INT NOT NULL,
siret BIGINT NOT NULL,
statutDiffusionEtablissement VARCHAR(1),
dateCreationEtablissement DATE,
trancheEffectifsEtablissement VARCHAR(2),
anneeEffectifsEtablissement INT,
activitePrincipaleRegistreMetiersEtablissement VARCHAR(6),
dateDernierTraitementEtablissement DATE,
etablissementSiege VARCHAR(5),
nombrePeriodesEtablissement INT,
complementAdresseEtablissement VARCHAR(40),
numeroVoieEtablissement INT,
indiceRepetitionEtablissement VARCHAR(1),
typeVoieEtablissement VARCHAR(4),
libelleVoieEtablissement VARCHAR(100),
codePostalEtablissement VARCHAR(5),
libelleCommuneEtablissement VARCHAR(100),
libelleCommuneEtrangerEtablissement VARCHAR(100),
distributionSpecialeEtablissement VARCHAR(26),
codeCommuneEtablissement VARCHAR(5),
codeCedexEtablissement VARCHAR(9),
libelleCedexEtablissement VARCHAR(100),
codePaysEtrangerEtablissement VARCHAR(5),
libellePaysEtrangerEtablissement VARCHAR(100),
complementAdresse2Etablissement VARCHAR(40),
numeroVoie2Etablissement INT,
indiceRepetition2Etablissement VARCHAR(1),
typeVoie2Etablissement VARCHAR(4),
libelleVoie2Etablissement VARCHAR(100),
codePostal2Etablissement VARCHAR(5),
libelleCommune2Etablissement VARCHAR(100),
libelleCommuneEtranger2Etablissement VARCHAR(100),
distributionSpeciale2Etablissement VARCHAR(100),
codeCommune2Etablissement VARCHAR(100),
codeCedex2Etablissement VARCHAR(9),
libelleCedex2Etablissement VARCHAR(100),
codePaysEtranger2Etablissement VARCHAR(5),
libellePaysEtranger2Etablissement VARCHAR(100),
dateDebut DATE,
etatAdministratifEtablissement VARCHAR(1),
enseigne1Etablissement VARCHAR(50),
enseigne2Etablissement VARCHAR(50),
enseigne3Etablissement VARCHAR(50),
denominationUsuelleEtablissement VARCHAR(100),
activitePrincipaleEtablissement VARCHAR(8),
nomenclatureActivitePrincipaleEtablissement VARCHAR(8),
caractereEmployeurEtablissement VARCHAR(1)
)
